#%RAML 0.8
title: API Using media type in the URL
baseUri: message://event/listener/message/cakeshop
version: v1
/example.event:
  post:
    body:
        application/vnd.framework.update-user+json:
            schema: !include json/schema/framework.update-user.json
            example: !include json/framework.update-user.json
